### ISSUE TITLE
Pub/Sub messaging

### ISSUE THREAD

**Issue by mlliarm** [datastacktv/data-engineer-roadmap#8]
Hello, 

Not sure how to edit a png to add a new pull request, so I'm creating this issue.

I believe [GCP's Pub/Sub](https://cloud.google.com/pubsub) messaging system deserves to be under the "Messaging" section too.

**Comment by alexandraabbas** [comment]
Hey @mlliarm, thanks for the suggestion! In my opinion if we include Google's PubSub then we should include Amazon SQS and/or SNS as well as Azure Service Bus. But that would be overwhelming so that's why I only included the open source options. Why do you think it would be necessary to include cloud based options?

Based on [Google trends](https://trends.google.com/trends/explore?geo=US&q=cloud%20pubsub,amazon%20sns,amazon%20sqs,azure%20service%20bus) Azure Service Bus is the most popular.

**Comment by mlliarm** [comment]
@alexandraabbas Hey, thanks for the reply ! 

Regarding your question, I believe it'd be important to add the relevant cloud options as it seems to me that this is the age where many people move  their on premise systems on the cloud. There are some [advantages](https://en.wikipedia.org/wiki/Cloud_computing#Characteristics) of having your pipelines on the cloud, I believe, where part of your system or whole of it is managed by the cloud provider (see difference between [IaaS](https://en.wikipedia.org/wiki/Infrastructure_as_a_service), [PaaS](https://en.wikipedia.org/wiki/Platform_as_a_service) and [SaaS](https://en.wikipedia.org/wiki/Software_as_a_service)). 

I understand that the infographic might get more overwhelming if all the cloud solutions would be added, but on the other hand I think that the prospect data engineer should know all the available options where he can choose from.
